In [3]:
# 1. 파이썬 문제
# - 입력받은 정수가 음수인지 양수인지 0인지 알려주세요.

x = int(input("원하는 수를 입력해주세요: "))
if x>0:
    print(x,"는 양수입니다")
elif x==0:
    print("0입니다")
else:
    print(x, "는 음수입니다")

원하는 수를 입력해주세요: 5
5 는 양수입니다


In [234]:
# - 'hello'를 지정한 횟수(0 <= n <= 3)만큼 출력해 보세요.

n = int(input("원하는 반복횟수를 입력하세요"))
if n <= 3 & n >= 0:
    for i in range(n):
        print("hello")
else:
    print("n의 범위는 0이상 3이하 입니다")

원하는 반복횟수를 입력하세요4
n의 범위는 0이상 3이하 입니다


In [26]:
# 0~9사이의 정수를 거꾸로 출력해 보세요.

# 방법1
list(range(10))[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [34]:
# 방법2
list(range(9,-1,-1))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [27]:
# - 임의의 리스트를 생성한 후, 리스트를 거꾸로 출력하는 반복문
import random

In [31]:
x = random.sample(range(100), 7)
x

[93, 15, 92, 20, 24, 74, 17]

In [37]:
for i in range(len(x)-1,-1,-1):
    print(x[i], end=" ")

17 74 24 20 92 15 93 

In [40]:
# - 리스트를 출력하면서 앞에 일련번호를 붙여주세요.

for i in range(len(x)):
    print(i, x[i])

0 93
1 15
2 92
3 20
4 24
5 74
6 17


In [43]:
# - 리스트에서 중복 값을 제거해 보세요.

ns = [1, 3, 5, 1, 3, 5, 1, 3, 5]
list(set(ns))

[1, 3, 5]

In [44]:
# numpy 연습문제
import numpy as np

In [50]:
# 1)랜덤하게 실수로 이루어진 5 x 6 형태의 데이터 행렬

xarr = np.random.randn(5,6)*3
xarr

array([[ 0.18004698,  1.01898539, -1.84729375, -3.76324518, -1.88380066,
        -1.01702554],
       [-0.48797399, -4.14390382,  1.23904501, -0.05105348, -4.68419486,
        -2.09008588],
       [-2.59994993, -4.54523055,  1.30014219,  2.63754252, -0.15777877,
         1.58605957],
       [ 0.61906017, -0.50996164,  0.68660489,  1.0914766 , -1.77271906,
        -0.24443264],
       [ 2.82571492, -1.85577529,  3.7580111 ,  1.20514247, -4.7917606 ,
        -2.77684248]])

In [55]:
# - 전체의 최댓값
xarr.max()

3.758011096401293

In [58]:
# - 각 행의 합
xarr.sum(axis=1)

array([ -7.31233277, -10.21816703,  -1.77921497,  -0.12997169,
        -1.63550989])

In [59]:
# - 각 행의 최댓값
xarr.max(axis=1)

array([1.01898539, 1.23904501, 2.63754252, 1.0914766 , 3.7580111 ])

In [60]:
# - 각 열의 평균
xarr.mean(axis=0)

array([ 0.10737963, -2.00717718,  1.02730189,  0.22397259, -2.65805079,
       -0.9084654 ])

In [61]:
# - 각 열의 최솟값
xarr.min(axis=0)

array([-2.59994993, -4.54523055, -1.84729375, -3.76324518, -4.7917606 ,
       -2.77684248])

In [62]:
# 2) 다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [63]:
# - 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

7

In [64]:
# - 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [69]:
# -이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,(1,2)]

array([6, 7])

In [70]:
# -이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[(1,2),2]

array([ 7, 12])

In [77]:
# -이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[(0,1),:][:,(3,4)]

array([[3, 4],
       [8, 9]])

In [106]:
# 3) 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.

x = np.zeros((3,5))
x[:,(3,4)] = 1
y = np.arange(1,16)*10
y = y.reshape(3,5)
res = np.vstack([x,y])
np.tile(res, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [107]:
# 4) 다음 행렬과 같은 배열이 있다.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [111]:
# -이 배열에서 3의 배수를 찾아라.
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [112]:
# -이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [114]:
# -이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x%3==0) & (x%4==1)]

array([9])

In [126]:
# 5) -동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을
# 파이썬으로 작성한다.

coin = []
for i in range(10):
    coin.append(random.randint(0, 1))
coin

[0, 1, 0, 0, 0, 1, 1, 0, 0, 1]

In [129]:
# numpy로 작성한 경우

np.random.randint(0, 2, size=10)

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [135]:
# 5) -주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
# 파이썬으로 작성한 경우

dice = []
for i in range(100):
    dice.append(random.randint(0, 6))
sum(dice) / len(dice)

2.74

In [137]:
# numpy로 작성하는 경우

np.random.randint(0, 7, size=100).mean()

2.8

In [156]:
# 6) 영어 성적을 기준으로 각 열(column)을 재정렬하라.
test = np.array([[  1,    2,    3,    4],
                 [ 46,   99,  100,   71],
                 [ 81,   59,   90,  100]])

test2 = test[:, test[1].argsort()]
test2

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [157]:
# 3. iris data 유사 데이터 추출
from sklearn.datasets import load_iris

In [158]:
iris = load_iris()

In [159]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [160]:
iris.data[0,:]  #첫번째 꽃 데이터

array([5.1, 3.5, 1.4, 0.2])

In [167]:
# 첫번째 꽃 데이터와 가장 유사한 꽃 데이터와 
# 그때의 유클리디안 거리를 출력

# iris.data 표준화
iris_z = (iris.data - np.mean(iris.data, axis=0)) / np.std(iris.data, axis=0)
iris_z

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [213]:
distance = np.sqrt(((iris_z[1:len(iris_z)+1] - iris_z[0])**2).sum(axis=1))
distance

array([1.17621868, 0.84560741, 1.10368502, 0.26013882, 1.03844415,
       0.66133116, 0.2662756 , 1.62082104, 0.96287744, 0.58934504,
       0.44502517, 1.21417696, 1.52012862, 1.43425477, 2.21208336,
       1.0259251 , 0.13163218, 1.02560028, 0.70531729, 0.46281731,
       0.53338619, 0.68681858, 0.63006343, 0.51564305, 1.16291333,
       0.38717219, 0.13383627, 0.26013882, 0.85131861, 0.99644652,
       0.50760619, 1.39387913, 1.68268935, 0.95383747, 0.71029472,
       0.48799276, 0.35922722, 1.4308722 , 0.23710977, 0.18772101,
       2.86002385, 1.09523808, 0.55211968, 0.79182411, 1.21417696,
       0.69988351, 0.91867093, 0.52337301, 0.47607127, 3.43367023,
       2.99848071, 3.53416564, 3.48510115, 3.42205118, 2.8855071 ,
       3.03977392, 2.95731658, 3.25816321, 2.81428991, 3.80409426,
       2.779454  , 3.66570053, 3.06413523, 2.43615079, 3.16368272,
       2.77931239, 2.75222742, 4.09446644, 3.01473784, 3.09624142,
       2.88878634, 3.78138011, 3.05211606, 3.03352513, 3.16712

In [202]:
len(distance)

149

In [221]:
min_distance = distance.min()
min_distance

0.13163218429030077

In [229]:
np.where(distance == min_distance)  #16

(array([16], dtype=int64),)

In [232]:
print(iris.data[17,:])  #iris.data에는 기준 식물에 대한 데이터가 포함되어 있으므로 => 17
print(min_distance)

[5.1 3.5 1.4 0.3]
0.13163218429030077
